"""Initial Schema with all models

Revision ID: 4537e4c5d37d
Revises: 
Create Date: 2026-02-07 10:38:57.485909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4537e4c5d37d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ball')
    op.drop_table('team')
    op.drop_table('player')
    op.drop_table('match')
    op.drop_table('innings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('innings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('batting_team', sa.VARCHAR(length=100), nullable=False),
    sa.Column('bowling_team', sa.VARCHAR(length=100), nullable=False),
    sa.Column('innings_number', sa.INTEGER(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['batting_team'], ['team.id'], ),
    sa.ForeignKeyConstraint(['bowling_team'], ['team.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('team2', sa.VARCHAR(length=100), nullable=False),
    sa.Column('over_limit', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['team1'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team2'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ball',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inning_id', sa.INTEGER(), nullable=False),
    sa.Column('over', sa.INTEGER(), nullable=True),
    sa.Column('balls', sa.INTEGER(), nullable=True),
    sa.Column('striker_id', sa.INTEGER(), nullable=False),
    sa.Column('non_striker_id', sa.INTEGER(), nullable=False),
    sa.Column('bowler_id', sa.INTEGER(), nullable=False),
    sa.Column('runs', sa.INTEGER(), nullable=True),
    sa.Column('wickets', sa.INTEGER(), nullable=True),
    sa.Column('extras', sa.INTEGER(), nullable=True),
    sa.Column('is_wicket', sa.BOOLEAN(), nullable=True),
    sa.Column('dismissed_player_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bowler_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['dismissed_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['inning_id'], ['innings.id'], ),
    sa.ForeignKeyConstraint(['non_striker_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['striker_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
